name: GitHub Actions Demo
run-name: sample
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["11"]
    steps:
      - name: Checking out
        uses: actions/checkout@v4
      - name: Java JDK for compilation
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven running
        run: mvn clean install

  publish-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Archive Jar
        uses: actions/upload-artifact@v4
        with:
          name: testing
          path: target/javaparser-maven-sample-1.0-SNAPSHOT-shaded.jar
